import type { Metadata } from 'next'
import { Karla, Nunito_Sans } from 'next/font/google'
import './globals.css'

const karla = Karla({
  variable: '--font-heading',
  subsets: ['latin'],
})

const nunito = Nunito_Sans({
  variable: '--font-paragraph',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${karla.variable} ${nunito.variable} antialiased`}>{children}</body>
    </html>
  )
}
